# Generated by Django 3.2 on 2022-03-26 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ean_code',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='load_index',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.manufacturer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.tyresize'),
        ),
        migrations.AlterField(
            model_name='product',
            name='speed_index',
            field=models.CharField(max_length=254),
        ),
    ]
