# Generated by Django 3.2 on 2022-03-26 23:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220326_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ean_code',
            field=models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(13)]),
        ),
    ]
