# Generated by Django 3.2 on 2022-04-17 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220326_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ean_code',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(13)]),
        ),
    ]
